### ISSUE TITLE
there is no printFile function?

### ISSUE THREAD

**Issue by binbinracing** [tojocky/node-printer#72]
I got an error while trying this code

  printer.printFile({filename:filename
      , printer:'HP_LaserJet_Pro_MFP_M125nw' // printer name, if missing then will print to default printer
      , printer: process.env[3]
    , success:function(jobID){
    console.log("sent to printer with ID: "+jobID);
  }
  , error:function(err){console.log(err);}
});

and i saw on lib, seem there is no printFile function. Can you update it? I need to print a HTML file.
Thanks

**Comment by tojocky** [comment]
What OS? Not sure that even cups on posix does support html file.

**Comment by binbinracing** [comment]
im using MacOsX 10.9.5, Mozilla FireFox newest version.
An error is 

TypeError: undefined is not a function

**Comment by tojocky** [comment]
OK, the example, was incorrect. please retry the last change: https://github.com/tojocky/node-printer/blob/master/examples/printFile.js .
Also bear in mind that I corrected getDefaultPrinterName in POSIX, but returning correct default printer name defined by user: https://github.com/tojocky/node-printer/commit/fe07b82952aa4267e0b03f6fd94fca90dc7bf13f

**Comment by binbinracing** [comment]
but seem the printer.printFile didn't exist. so an error still happens.
should i upgrade to the lastest version?

**Comment by tojocky** [comment]
yes please.

Could you please whole error exception?

**Comment by binbinracing** [comment]
i saw your latest version is 0.1.2, but when trying to reinstall "npm install printer" its only 0.1.1
How could i use the latest version? did you update it on node?
oh and it just said app crashed
"28 May 22:44:14 - [nodemon] app crashed - waiting for file changes before starting..."

**Comment by tojocky** [comment]
Use command: `npm install git+https://github.com/tojocky/node-printer.git`

**Comment by tojocky** [comment]
GIT version resolved some crash issues.

**Comment by binbinracing** [comment]
its work perfectly!
Thank you.

**Comment by tojocky** [comment]
you have to convert into PDF

**Comment by binbinracing** [comment]
good idea.
i've found out an applet java that helping us to print html. i think you can consider it.
http://qzindustries.com/

anw, thank you! Great job!

**Comment by matheuslcampos** [comment]
i tried get printers but the error appears: printer.getdefaultprintername() is not a function
